### ISSUE TITLE
Adding additional ROM folders

### ISSUE THREAD

**Issue by SRC267** [seleuco/MAME4droid-2024#2]
So I have a separate folder for SNK Neo Geo titles, i don't really want to merge them with Arcade ROMs, because I set it like that for the RetroArch app playlist. 

I checked general settings > configure folders, but there's no way to navigate to the location on the SD card, this isn't an issue with PC MAME, you are able to add more folder directories.

It will be nice to add it from the mame4droid settings where it says change ROMs path.

**Comment by seleuco** [comment]
This version of android has scoped storage implemented. If you choose the option to install on the SD then MAME4droid is using scoped storage that allows the reading of the ROMs safely and that allows it to be published on Google Play with SD support something that Retroarch does not have. 

Access using scoped storage is slow and difficult to implement. For it to work minimally well, the ROM directory is read and saved for future readings. Implementing multiple directories for each thing would be crazy to implement and bad for the user experience as you would have to request multiple permissions. 

It is for this reason that I decided to have a single roms directory but with the possibility of defining other things such as artworks or samples in subdirectories within the ROMS directory.

Unfortunately I can't define more things (other subdirectories than artwork, samples, software)  without modifying the MAME code base which I don't want to do to be able to easily update to new versions.

The only way I can think of is to modify the mame.ini file (conecting to your phone by ADB on PC) so you can define another roms subdirectory within the roms subdirectory (for neogeo) that is already defined on the SD. I have not tried this with ROMS recursion but I have tried it to add icons, snapshots, etc. and it has worked for me.

Example: assumption than your roms are in SD at /storage/emulated/0/MAME4droid) and your installation is /storage/emulated/0/Android/data/com.seleuco.mame4d2024/files


1/ create the mame.ini:  Go to general settings and press save settings it will be created at /storage/emulated/0/Android/data/com.seleuco.mame4d2024/files

2/ search for:

#
# CORE SEARCH PATH OPTIONS
#
homepath                  .
rompath                   "/storage/emulated/0/MAME4droid;./roms"

3 / add the new rompath /storage/emulated/0/MAME4droid/neogeo

then rompath wil be:

rompath                   "/storage/emulated/0/MAME4droid;./roms;/storage/emulated/0/MAME4droid/neogeo"

Tell me if works :)

**Comment by seleuco** [comment]
any news about it? finally work for you? You  can also try as MAME4droid has permission for /storage/6631-6132/Games/MAME refactor to /storage/6631-6132/Games/MAME/mainroms and /storage/6631-6132/Games/MAME/NeoGeoROMs

**Comment by SRC267** [comment]
No luck, tried different combinations and even tried adding a . between > ;/

**Comment by seleuco** [comment]
When I have a little time. I will try on my device.

**Comment by seleuco** [comment]
Ok. I realized where the problem was. Its very stupid :). I'm setting the paths in the emulator and that takes precedence over the mame.ini file. 

I just deployed a new version 1.6.6 which will be available in a few hours that has a new  option  on advanced settings that you can enable to disable this behavior and so the mame.ini  paths will be read. I have tried it and it has worked correctly for me. I have created a "main" directory and another "others" directory hanging from the original previusly authorized directory in the SD.

When you can download the application and try it, confirm to me that it is solved ;)

**Comment by SRC267** [comment]
Okay so I updated the app, opened advanced settings and enabled the new mame.ini option for paths. 

Here's the full line for rompath in the mame.ini text file: /storage/6631-6132/Games/MAME;./roms;/storage/6631-6132/Games/NeoGeo

It still doesn't show the NeoGeo titles in the menu. Unless I've messed the path up, does it look okay to you? Initially the folder was SNK - Neo Geo, that's my preferred folder title, then changed it to NeoGeo, to see if it helped fix it, but still no luck.

**Comment by seleuco** [comment]
¿are they showed now in mame ui configure folders? mine yes.

first try something simple  ... something like i did:

my original authorized path was /storage/emulated/0/MAME/

i added a new "main" and "others" so my rompath is now is (i dont have others inside main. My roms directories are siblings)

rompath                   /storage/emulated/0/MAME/main;/storage/emulated/0/MAME/others;./roms

**Comment by SRC267** [comment]
No, it doesn't work. Tried different ways, and removed data to try again. I have both paths on the SD card. Maybe that's why it's acting up

**Comment by seleuco** [comment]
I think you are doing something wrong. One thing I think you can get wrong is that you need to have the parent directory authorized. You have to selec it in the change rom path option from Mame4droid the directory that will contain the two new directories. the one from the normal mame roms and the other from neogeo. Is not, Mame4droid will not see Them because the parent directory is not authorized to be read. 
 
/storage/6631-6132/Games/ should be selected in change rom path.

**Comment by SRC267** [comment]
![mame.ini paths](https://github.com/seleuco/MAME4droid-2024/assets/140402431/1c60e765-6c0b-4a53-9208-01aa37dce707)

Here's the ini path I've set, I have it ticked in the app, the menu is now blank when I selected change rom paths in general, as the ini should override that. 

![Menu path settings](https://github.com/seleuco/MAME4droid-2024/assets/140402431/3bced9e3-e940-4336-8503-93a26bcc4e13)

**Comment by seleuco** [comment]
Not.  You are confusing "installation path" with "ROMs path". Installation path is were the mame assets are installed. You shouldn't touch that. You should leave it as it was at the beginning. If you don't remember, uninstall the application completely. Touching this option makes the mame.ini file different instead of the one you were originally modifying. Also, if the path is not writable you will have reading problems.

You have to point "general->change ROMS path" to /storage/6631-6132/Games

you have to set in mame ini:

/storage/6631-6132/Games/main;/storage/6631-6132/Games/NeoGeo;./roms

where "main" has your main mame roms and "neogeo" has your neogeo roms.

Ensure you hace enabled"advanced -> use mame.ini fo paths" if you do an uninstall. 

If you have a lot of files inside  "/storage/6631-6132/Games" it will be slow the launch of mame4droid as it has to caching all files inside "Games" and if you have not enouth memory it could hung. In this case, you should use a diferent folder structure aproach like  pointing to".... Games/MAME" with "... Games/MAME/main" and "... GAMES/MAME/NeoGeo" in the mame ini.

**Comment by SRC267** [comment]
This did the trick. Finally. The mistake I made was opening the MAME folder as the path and not the Games one, selecting Games as the main one rectified the issue.

**Comment by FlykeSpice** [comment]
I think it would be better, instead of just reserving the user selected folder for roms, the selected folder will be where Mame's root'll be installed (roms, bios, where saves and ini configurations will be located).

Keeping aside mame configurations files & saves on an inacessible internal directory is a bad idea, the user can't transfer the save files and customize the configuration files, it would be better overall making the public folder mame's root.

**Comment by SRC267** [comment]
Hi again, in one of your updates to the app it said to uninstall/reinstall to get changes to the UI, I did that. It helped with my database scraping so that was helpful, because prior to that it wasn't working, despite having my ROMs on the external storage. Anyways for some reason it's not picking up my Neo Geo folder anymore. I backed up my old mame.ini file before uninstalling, installed MAME, set it all up again, replaced the new mame.ini file with the old one,  made sure to toggle the advanced setting to use MAME.ini 

![Screenshot_20240602-200904.png](https://github.com/seleuco/MAME4droid-2024/assets/140402431/2e94af8d-4605-4080-84b9-2a6115882221)

Maybe something has changed to the structure in which the app reads them?

![Screenshot_20240602-201227.png](https://github.com/seleuco/MAME4droid-2024/assets/140402431/b5471204-6b82-4157-a95e-090e227f3a64)

**Comment by seleuco** [comment]
Hi...

I don't consciously change anything that could affect that. :?

The only thing I can think of is that it could be something about permissions. Recreate the mame.ini from the application itself by deleting you backed one and put your paths again.

It is normal that scraping works for you now since it only looks at files in the default path. It is assumed that if you are an advanced user and have access to the directories, it is best for you to upload the images you want directly. 

It is assumed that if you are an advanced user and have access to the directories, it is best for everyone to upload the images they want. It also complicated things a lot and most people would not take advantage of having a more sophisticated scraping system.

**Comment by seleuco** [comment]
You are missing something... :?

**Comment by SRC267** [comment]
Fixed. Yea, had it already set to external. However I had it set to just  the MAME fodler rather than the entire Games folder. Rookie mistake!

**Comment by JJWatMyself** [comment]
This has been a really helpful thread to read after battling with this for an hour. When I implemented on desktop mame.ini was the key.  For Android, the ability to transfer between systems can be really helpful, and mame.ini could be an important part of how to accomplish. I'd be fine with copying mame.ini as part of setup. Maybe in the Advanced menu you could display the path for mame.ini upon selecting the option.

I plan to test with all the artwork "extras". A complete extras on a full ROM set is about 8GB. It'll be interesting to see the result.

**Comment by JJWatMyself** [comment]
I also see the menu option for built in Scraping. Holy-wow, I might give that a test also.

**Comment by JJWatMyself** [comment]
I did some testing early this morning.  So far pretty good. Points of feedback.

1) mame.ini is not created until select 'Save Settings' from the UI menu
2) iconpath appears to be ignored from mame.ini. I'll resist initiating a Scrape as the files will be in the wrong place.
3) state_directory does not appear to be displayed in the UI.  I'll test a save to see if it appears.

Here is the top section of the mame.ini

`#
# CORE CONFIGURATION OPTIONS
#
readconfig                1
writeconfig               0

#
# CORE SEARCH PATH OPTIONS
#
homepath                  .
rompath                   /storage/0123-4567/Games/MAME/roms/mame0272-full
hashpath                  hash
samplepath                /storage/0123-4567/Games/MAME/samples
artpath                   /storage/0123-4567/Games/MAME/artwork
iconpath                  /storage/0123-4567/Games/MAME/icons
ctrlrpath                 ctrlr
inipath                   .;ini;ini/presets
fontpath                  .
cheatpath                 cheat
crosshairpath             crosshair
pluginspath               plugins
languagepath              language
swpath                    software

#
# CORE OUTPUT DIRECTORY OPTIONS
#
cfg_directory             cfg
nvram_directory           nvram
input_directory           inp
state_directory           /storage/0123-4567/Games/MAME/sta
snapshot_directory        /storage/0123-4567/Games/MAME/snap
diff_directory            diff
comment_directory         comments
share_directory           share
`

**Comment by JJWatMyself** [comment]
It also appears to ignore these values:

```
artwork_previewpath       /storage/0123-4567/Games/MAME/artwork_preview
titlespath                /storage/0123-4567/Games/MAME/titles
cpanelpath                /storage/0123-4567/Games/MAME/cpanel

```

**Comment by JJWatMyself** [comment]
I have submitted as a new issue here: [https://github.com/seleuco/MAME4droid-2024/issues/69](url)

**Comment by udance4ever** [comment]
@seleuco thank you for all your excellent support (and an amazing app all these years, been there from the beginning :)

im on a Pixel 6a (no micro SD) and confirm giving permissions to the parent folder (`/storage/emulated/0`) lets MAME4droid find BIOS files where Batocera Linux expects them (I use Syncthing to keep my roms synced)
```
rompath                   /storage/emulated/0/roms/mame;/storage/emulated/0/bios/mame;/storage/emulated/0/bios;./roms
```
yes, there is the cost of searching my whole internal drive (I could create a new parent `emu` directory to reduce this cost) but it's not that bad & just going to post a win for cross-platform workability - thank you! 🙏🏼

**Comment by guest1984** [comment]
Sorry if this has already been answered, but where does the mame.ini go? selecting 'save settings' in general settings does not create one.

I have tried the following in a 'mame.ini' located in the root of my mame folder.  
rompath /storage/2AE4-057B/ROMS/mame/;/storage/2AE4-057B/BIOS/mame/;/storage/2AE4-057B/BIOS;./ROMS

I have also tried moving system bios to /storage/2AE4-057B/ROMS/mame/bios/
